# Generated by Django 2.2 on 2019-04-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190421_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotacredit',
            name='credit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
